// <auto-generated />
namespace SolucionesARWebsite2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _011 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_011));
        
        string IMigrationMetadata.Id
        {
            get { return "201306180330212_011"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
