// <auto-generated />
namespace SolucionesARWebsite2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _006 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_006));
        
        string IMigrationMetadata.Id
        {
            get { return "201306020551156_006"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
