// <auto-generated />
namespace SolucionesARWebsite2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _008 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_008));
        
        string IMigrationMetadata.Id
        {
            get { return "201306070551538_008"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
