// <auto-generated />
namespace SolucionesARWebsite.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _014 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_014));
        
        string IMigrationMetadata.Id
        {
            get { return "201212151950286_014"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
